spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://stg-yswa-kr-practice-db-master.mariadb.database.azure.com:3306/S10P23A504?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: S10P23A504@stg-yswa-kr-practice-db-master
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
    #    properties:
    #      hibernate:
    #        show_sql: true
    #        format_sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 100


  data:
    redis:
      host: 172.17.0.1
      port: 6379

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: # 발급 받은 client ID
            client-secret: # 발급 받은 Client Secret
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            scope: # 기본 값 openid,profile,email => email 로 설정 변경
              - email
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
#          naver:
#            client-name: Naver
#            client-id: # 발급 받은 Client ID
#            client-secret: # 발급 받은 Client Secret
#            client-authentication-method: client_secret_post
#            authorization-grant-type: authorization_code
#            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
#            #            scope:
#            #              - email
#
#
#          kakao:
#            client-name: Kakao
#            client-id: # 발급 받은 Client ID
#            client-secret: # 발급 받은 Client Secret
#            client-authentication-method: client_secret_post
#            authorization-grant-type: authorization_code
#            scope: # https://developers.kakao.com/docs/latest/ko/kakaologin/common#user-info
#              - account_email
#            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
#
#        provider:
#          naver:
#            authorization-uri: https://nid.naver.com/oauth2.0/authorize
#            token-uri: https://nid.naver.com/oauth2.0/token
#            user-info-uri: https://openapi.naver.com/v1/nid/me
#            user-info-authentication-method: header
#            user-name-attribute: response # Naver 응답 값 resultCode, message, response 중 response 지정
#
#          kakao:
#            authorization-uri: https://kauth.kakao.com/oauth/authorize
#            token-uri: https://kauth.kakao.com/oauth/token
#            user-info-uri: https://kapi.kakao.com/v2/user/me
#            user-info-authentication-method: header
#            user-name-attribute: id # Kakao 응답 값 id, connected_at, properties, kakao_account 중 id 지정

logging:
  level:
    root: info

cloud:
  aws:
    credentials:
      access-key: AKIAT23F3XWNRKCFWFQZ
      secret-key: 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
    s3:
      bucket: togeduck
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
decorator:
  datasource:
    p6spy:
      enable-logging: true

jwt:
  secret: 4f9c90be9fcbdc27809c3fcdf19d9fca27a8a713af2b360d1753c3f3680fe825d30ca30de7df1b2318907cd0da174a8dd3d049b0772bace55e57347cd2cfa0f4
#  access-token-validity-in-seconds: 1000 * 60 * 60 # 1시간
#  refresh-token-validity-in-seconds: 1000 * 60 * 60 * 24 * 7 # 일주일

openai:
  model: gpt-3.5-turbo
  api:
    url: https://api.openai.com/v1/chat/completions
    key: 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